# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demoall
    # (this is just an example, not intended to be a production configuration)
    ports:
      - "4091:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"